### ISSUE TITLE
 Unexpected error in setup_connection(): could not convert string to float: '8.0.1'

### ISSUE THREAD

**Issue by tomascrespo** [beveradb/sonoff-lan-mode-homeassistant#72]
Hi! I've just installed this component. It will be wonderfull for my setup.

I get the module loaded and the entity created, but I can use it. I have a lot of this errors on log:
`2019-07-29 23:56:13 ERROR (MainThread) [homeassistant.components.switch.sonoff_lan_mode] Unexpected error in setup_connection(): could not convert string to float: '8.0.1'`

Any idea?

My Home Assistant is 0.96.5 on Raspbian Buster

PD: In README of this project should say that you have to download manifest.json file too, not only switch.py

**Comment by mattsaxon** [comment]
This is due to using WebSockets 8.0.1, the string '8.0.1' cannot be converted to a float.

@tomascrespo, how did websockets 8.0.1 get installed, HA uses WS 6.0

**Comment by tomascrespo** [comment]
I have no idea. Could it be related with Python version?

I upgraden (manually) to Python 3.7, but I don't have any other custom installation. 

Any solution?

**Comment by mattsaxon** [comment]
If you are happy to do such manual installations, an easy fix would be to do a specific install of WS 8.0. If that causes other issues it should be easy to regress

**Comment by mattsaxon** [comment]
I'd recommend trying "pip install websockets==8.0". However note that this component to my knowledge has only been tested with 6.0 and 7.0

**Comment by tomascrespo** [comment]
I've just done:
` pip install 'websockets==6.0.0' --force-reinstall`
And now I have websockets 6.0.0. Now I'm having the message in the log.

However I can't get my sonoff POW R2 (firmware 3.3.0) working. In Developer tools -> States I get 'unavailable' as state for the sonoff. I've created a entity-button card action and it does nothing.

My configuration.yaml:
```
switch:
  - platform: sonoff_lan_mode
    name: Depuradora
    host: 192.168.2.190
    icon: mdi:pool
```
My card:
```
entity: switch.depuradora
hold_action:
  action: more-info
show_icon: true
show_name: true
tap_action:
  action: toggle
type: entity-button

```

The sonoff is on LAN mode, becaus I can only accessit on WiFi, not on mobile data

**Comment by mattsaxon** [comment]
This component only support firmware 1.8 and 2.x

You need to use my fork for firmware 3.x.

**Comment by tomascrespo** [comment]
I have run your test script:
```
pi@ICC-Solar:~ $ python3 test_sonoff.py
2019-07-30 16:23:37 - DEBUG - Sonoff class initialising
2019-07-30 16:23:37 - DEBUG - initializing websocket
2019-07-30 16:23:37 - INFO - WebsocketListener initialising, connecting to host: ws://192.168.2.190:8081/
2019-07-30 16:23:37 - DEBUG - attempting to call WebSocketApp run_forever with ping_interval: 145
```
and it stops at this point

**Comment by tomascrespo** [comment]
> 
> 
> This component only support firmware 1.8 and 2.x
> 
> You need to use my fork for firmware 3.x.

I will give it a try

**Comment by mattsaxon** [comment]
When you say my component, do you mean mine @mattsaxon or @beveradb. This repo is @beveradb’s not mine.

Your switch is firmware 3.x, so you cannot use the code in this repo. Please use my fork of the repo

**Comment by tomascrespo** [comment]
> 
> 
> When you say my component, do you mean mine @mattsaxon or @beveradb. This repo is @beveradb’s not mine.
> 
> Your switch is firmware 3.x, so you cannot use the code in this repo. Please use my fork of the repo

I realaised now. All my test until this point were with @beveradb repo.

Now I'm testing @mattsaxon repo. One thing. In your fork, should I block the sonoff of connecting to the internet?

In your README you say: 
```
switch:
  - platform: sonoff_lan_mode_r3
    name: // Switch Name
    device_id: // **Local IP** address of device
    api_key: // [Optional] Custom icon for device
```

Local IP? or device ID? I think is Device ID, because there is an example above.

**Comment by tomascrespo** [comment]
This is my configuration.yaml with @mattsaxon repo:
```
switch:
  - platform: sonoff_lan_mode_r3
    name: Piscina
    device_id: 1000916149
    api_key: 123b1213-2fa6-4ef2-a27c-718fae8ec06d
    icon: mdi:pool
```

And now I getting this errors:
```
2019-07-30 16:43:39 ERROR (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] Error decrypting for device 1000916149: Invalid base64-encoded string: number of data characters (249) cannot be 1 more than a multiple of 4, probably wrong API key
2019-07-30 16:44:13 ERROR (zeroconf-ServiceBrowser_eWeLink_1000916149._ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] Error decrypting for device 1000916149: Invalid base64-encoded string: number of data characters (249) cannot be 1 more than a multiple of 4, probably wrong API key
2
```
